# Exercises for Vectors 1

In [44]:
print("Hello")

Hello


# ***Hi. I reallyu did not understand this !***

# Exercise 1

The following code creates some vectors, but when executed it issues an error:

"NameError: name 'np' is not defined"

What could be the cause of it? See slide "Creating  Vectors In NumPy​"...

Correct the code to be able to run it!

In [1]:
# Insert your correction here
import numpy as np
# a vector as a Python list datatype
asList = [1,2,3]

# same numbers, but as a dimensionless numpy array
asArray = np.array([1,2,3])

# again same numbers, but now endowed with orientations
rowVec = np.array([ [1,2,3] ]) # row
colVec = np.array([ [1],[2],[3] ]) # column

# Note the use of spacing when defining the vectors; that is not necessary but makes the code more readable.

# Exercise 2

After correcting the notebook, you will be able to check the shape of the created vectors with the following code.
     

In [2]:
# Check the sizes of the variables
print(f'asList:  {np.shape(asList)}') # using np's shape function
print(f'asArray: {asArray.shape}') # using a method associated with numpy objects
print(f'rowVec:  {rowVec.shape}')
print(f'colVec:  {colVec.shape}')

asList:  (3,)
asArray: (3,)
rowVec:  (1, 3)
colVec:  (3, 1)


Check the API definition of the **type** funtion in Python and call it on asList, asArray, rowVec, and colVec.

In [5]:
# Your solution here
print(type(asList))
print(type(asArray))
print(type(rowVec))
print(type(colVec))

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


What is the meaning of the different results?

The first one is a list the other ones are numpy arrays 

# Exercise 3
 Create two row vectors u and v, where u contains the elements 2 and 5 and v contains the elements 1 and 3. Create also two column vectors  x and y where x contains elements 3, 4, and 7; and y contains elements 2, 8, and 3.

In [20]:
# Row vectors
u = np.array([[2,5]])
v = np.array([[1,3]])

# Column vectors
x = np.array([[3],[4],[7]])
y = np.array([[2],[8],[3]])

# Exercise 4
Calculate the following operations:


*   u + v
*   u - v
*   x + y
*   y - x

In [8]:
print(u+v)
print(u-v)
print(x+y)
print(y-x)

[3 8]
[1 2]
[[ 5]
 [12]
 [10]]
[[-1]
 [ 4]
 [-4]]


# Exercise 5
Given a scalar λ = 4. Multiply λ by x.

In [9]:
print(4*x)

[[12]
 [16]
 [28]]


# Exercise 6


Check the documentation of the function [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html).

Create a row vector with 5 zeros and a column vector with 2 zeros.

In [ ]:
np.zeros(5)
np.zeros(2,1)

# Exercise 7

Create a new vector vT, that is the vector transpose of vector v.

Create a new vector xT, that is the vector transpose of vector x.

Print all 4 vectors.

In [21]:
vT = v.T
xT = x.T

print(v)
print("\n")
print(vT)
print("\n")
print(x)
print("\n")
print(xT)


[[1 3]]


[[1]
 [3]]


[[3]
 [4]
 [7]]


[[3 4 7]]


## Exercise 8

Given vectors a and b defined below:

```
a = np.array([1, 2, 3])
b = np.array([[10],
              [20],
              [30]])
```
when we print their sum

```
print(a+b)
```
We obtain the following array as a result:
```
[[11 12 13]
 [21 22 23]
 [31 32 33]]
```

What is the meaning of this operation? Is this a valid operation of Linear Algebra? You can build your argument from the NumPy [documentation](https://numpy.org/doc/stable/user/basics.broadcasting.html).



This is broadcasting. It makes sure that the vectors are the same shape aka it makes a matrix

# Exercise 9

Calculate the norm of vector w.

In [24]:
w = np.array([[8],[6],[28]])
print(np.linalg.norm(w))

29.732137494637012


# Exercise 10

Create a Python function "toUnit" that will take a vector as input and output a unit vector in the same direction.

Hints:

*   Check how to define functions in this [link](https://www.w3schools.com/python/python_functions.asp)
*   Learn the different arithmetic operators in [here](https://www.w3schools.com/python/gloss_python_arithmetic_operators.asp)


Try your function with vector w. Do not forget to check that the norm of the output vector is indeed 1.

What happens when you input the zeros vector?


In [30]:
def toUnit(vector):
    return (vector/np.linalg.norm(vector))

print(toUnit(w))
print(np.linalg.norm(toUnit(w)))

[[0.26906912]
 [0.20180184]
 [0.94174191]]
1.0


## Exercise 11
Given a and b defined below.

Calculate the dot product of a and b.


In [31]:
a = np.array([[1,2,3]])
b = np.array([[4],[5],[6]])

# Your solution here
print(np.dot(a,b))

[[32]]


# Exercise 12

The dot product is commutative, so if you compute the dot product of b and a you would expect the same result. That is 32.

What happened when you computed the dot product of b and a?

Get a hint on why that happens on the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)


Could you solve this issues by using the vector transpose?

## Svar
Det ser ud til at være ligesom broadcast, hvis jeg transposer b får jeg nok et svar der ligner det jeg vil ha, da de så er samme form.

In [42]:
print(np.dot(b,a))

[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [43]:
print(np.dot(b.T, a.T))

[[32]]


Det var ikke hvad jeg havde forventet. Jeg skulle transpose begge vectorer for at på det til at fungere. 

Det giver mening i den forstand at dimentionerne af vectorerene bliver byttet rundt så de er ligesom i np.dot(a,b). 

Dog forstår jeg ikke hvorfor de ikke fungerer normalt hvis jeg kun transposer 1.