# Lesson 5 - exercises for matrices part 2

In [1]:
import numpy as np

# Exercise 1



Construct the 3x3 identity matrix and the 3x3 zero matrix.
Before doing any calculations with python, try to think about what the
norm and the trace of both matrices would be? (write it down!)

Then use python to calcuate both the norm and the trace of these two matrices.
Does the result corresponds with your expectations.

Consider what the rank of these two matrices should be?
Calculate it using python for both of them and see if it corresponds to your expectations.

In [ ]:
idMatrix = np.eye(3)
zeroMatrix = np.array([[0,0,0],[0,0,0],[0,0,0]])

print(idMatrix)
print(zeroMatrix)

# I think the traces are 3 and 0
# I think the norms are \sqrt(3) and 0

print(np.trace(idMatrix))
print(np.trace(zeroMatrix))
print()
print(np.linalg.norm(idMatrix))
print(np.linalg.norm(zeroMatrix))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
3.0
0

1.7320508075688772
0.0


# Exercise 2

Construct a 2x2 and a 3x3 and a 4x4 diagonal matrix (i.e. only values on the diagonal - you choose which, but is should not be the identity matrix), the rest is zero in the matrix
Compute the rank of these 3 matrices.
Consider the results, and come up with an argument to why you get these results

# Exercise 3

1. Calculate the determinants of these 3 matrices from exercise 2.

  Notice, that the results may look at little "weird" due to floating point calculations giving rounding errors, so use round(x) on the result

  Look at the determinant values for each matrix and see if you can come up with a formula for how to calculate the determinat of a diagonal matrix (it's much easier than the general determinant formula!)

2. Find the determinant of M defined below. Give a reason for your result.


In [ ]:
 M = np.array([[1, 0, 0, 0],
              [0, 2, 0, 0],
              [0, 0, 3, 0]])

# Exercise 4

Calculate the norm of the 3 matrices from exercise 3 using python

Try to come up with a general formula for calculating the (Frobenius) norm of a diagonal matrix based on your results

# Exercise 5

Solve exercise 6-5 in the book.



In [ ]:
#hint - in order to create a random matrix with specified dimensions M and r you can do this (define M and r before)

A = np.random.randn(M,r)

# Exercise 6

Solve exercise 6-6 in the book.

Hint: An easy way to create a rank-1 matrix is to create a 1x4 matrix for instance, where all values except 1 is zero.

The trick is to construct the to matrices, A and B in each of the 3 cases, both with rank 1, in a "clever" way, so that the rank of A+B in each instance is rank 0, rank 1 and rank 2.

It's optional if you want to try it out with multiplication instead.

# Exercise 7

Solve exercise 6-8 from the book.
You can try it out with different A matrices to see that it still holds

# Exercise 8

Solve exercise 6-9 from the book

In [ ]:
#hints - you can easily create random matrices and vectors of any size desired

A = np.random.randn(4,3)
v = np.random.randn(4,1)

#In order to check if a vector is part of the column space, we can
#simply "append" the vector v to A, calling this matrix A_V, such that
#A_V contains an extra column with v - in python this can be done like this:

A_V = np.hstack((A,v))

#Now if the ranks of A and A_V are the same, then v is in the column space.
#If they are different, v is not in the column space.

#Why is that the case?
