# Exercises for Vectors 2

# Exercise 1

Create a column vector v of dimension 2 of your choice. Then create a vector w containing the values of v multiplied by 5. You can represent the vector set containing v and w as V = [v,w].



In [3]:
import numpy as np

v = np.array([[1],[2]])
w = v*5
print(w)
V = [v,w]

[[ 5]
 [10]]


# Exercise 2

The following code should return:


```
array([[ True],
       [ True]]).
```

    

In [4]:
w == 5 * v

array([[ True],
       [ True]])

# Exercise 3

Is the set V linearly dependent or independent? Justify your answer with a short sentence (max 20 words).

Since $$v=\begin{bmatrix} 1 \\ 2 \end{bmatrix}$$ and $$w=\begin{bmatrix} 5 \\ 10 \end{bmatrix}$$ then $$w=5\cdot v$$

Therefore the $V$ set is linearly dependent.


# Exercise 4

Please provide a set W with two column vectors of dimension 3 that are linearly independent.

In [8]:
x = np.array([[1],[4],[2]])
y = np.array([[6],[9],[2]])
W = [x,y]

# Exercise 5
In the following we have defined "lindcheck", a function that can be used to check if a vector set is linearly independent.

As it is, you should obtain the result True in case your vectors x,and y are correctly linearly independent.

You should also obtain the False if you try to pass the space V.

Obs. "lindcheck" works by contructing a matrix and computing its rank. We will talk about this in the Matrices part 2 lecture, so you are not expected to understand how it works now.

In [9]:
def lindcheck(vectors):
    matrix = np.column_stack(vectors)
    rank = np.linalg.matrix_rank(matrix)
    return rank == len(vectors)

print(lindcheck(W))

True


# Exercise 6

In the following code, change the values of the lambdas (l1 and l2) such that  the vector (1,1,2) is the result of the linear combination of v1 and v2.

In [6]:
v1 = np.array([[1], [1], [0]])
v2 = np.array([[1], [1], [1]])
l1 = -1
l2 = 2
print(l1*v1+l2*v2)

[[1]
 [1]
 [2]]


# Exercise 7

What is the subspace spanned by the vector v2?

$$\lambda\begin{bmatrix}1\\1\\1\end{bmatrix}, \lambda \in \mathbb{R}$$

# Exercise 8

Explain in your words what is the formal definition of a basis.

The set of all basic vectors that are needed to span the whole space. For example for a 2d plot $$S_2=\begin{Bmatrix}\begin{bmatrix}1\\0\end{bmatrix},\begin{bmatrix}0\\1\end{bmatrix}\end{Bmatrix}$$

Every point in the 2d space can be reached by scaling and combining these two vectors 

# Exercise 9

What is the relation between the dimensionality of a vector and the number of vectors in a basis for the space containing all vectors of such dimension?

Hint:
* Start with some known cases. For instance, given vector v defined in Exercise 1. What is its dimensionality? What is a basis for the space containing v?
* After establishing the realtion for vectors of dimension 2, 3,... generalize to the case of vectors of dimension n.

# Exercise 10

Define a function to plot the standard basis vectors of $\mathbb{R}^2$.

# Exercise 11

Add to your plot the vector v you defined at the begining of the exercise sheet.

# Exercise 12

Can you define a basis for ℝ⁴? Is it the standard basis? If yes, provide another basis.