Most of the following exercises will be from book, so the numbers mentioned will reference these exercises. They start on page 76. You can solve them in this notebook and continue to work in it (make a copy first, so you can edit it)

# Exercises - matrices part 1

In [3]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt

# for null spaces
import scipy.linalg

# a pretty-looking matrix from scipy
from scipy.linalg import toeplitz


# NOTE: these lines define global figure properties used for publication.
from IPython import display
display.set_matplotlib_formats('svg') # print figures in svg format
plt.rcParams.update({'font.size':14}) # set global font size

/var/folders/18/w1gps92x1kzbq_r1gl0_637r0000gn/T/ipykernel_21016/3966143812.py:14: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  display.set_matplotlib_formats('svg') # print figures in svg format


# Exercise 1

Solve exercise 5-1 from the book.

In [4]:
A = np.arange(12).reshape(3,4)
print(A)

elementA = A[1,3]

print(elementA)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7


# Exercise 2



Solve exercise 5-2 from the book (the numbers in the matrix goes from 0-99 in a 10x10 matrix). You can skip the visualization part of the exercise and come back to it later

In [5]:
C = np.arange(100).reshape(10,10)

C1 = C[0:5,0:5]
print(C1)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


# Exercise 3


Solve the first part of exercise 5-3. (so only extract the other four 5x5 blocks, not the reorganized part)

In [6]:
C1 = C[0:5,0:5]
C2 = C[0:5,5:10]
C3 = C[5:10,0:5]
C4 = C[5:10,5:10]

print(C1)
print()
print(C2)
print()
print(C3)
print()
print(C4)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]]

[[50 51 52 53 54]
 [60 61 62 63 64]
 [70 71 72 73 74]
 [80 81 82 83 84]
 [90 91 92 93 94]]

[[55 56 57 58 59]
 [65 66 67 68 69]
 [75 76 77 78 79]
 [85 86 87 88 89]
 [95 96 97 98 99]]


# Exercise 4

Solve exercise 5-4 in the book.

Hints: to do the double for loop, it will look something like this in python:


In [7]:
def addMatrices(A,B):
    C = np.zeros(A.shape)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            C[i,j] = A[i,j] + B[i,j]
    return C


print(addMatrices(C1,C2))

[[ 5.  7.  9. 11. 13.]
 [25. 27. 29. 31. 33.]
 [45. 47. 49. 51. 53.]
 [65. 67. 69. 71. 73.]
 [85. 87. 89. 91. 93.]]


# Exercise 5


Solve exercise 5-5 in the book
Print out the 3 expressions (first, middle and last expression on the equation line) and compare them.

How would you compare if two matrices are equal? (or almost equal, there can be rounding issues).

In [ ]:
lambdaScale = np.random.random()

A = np.random.randn(3,4)
B = np.random.randn(3,4)

print(lambdaScale*(addMatrices(A,B)))
print()
print(addMatrices(lambdaScale*A,lambdaScale*B))
print()
print(addMatrices(lambdaScale*B,lambdaScale*A))

AB1 = np.absolute(lambdaScale*(addMatrices(A,B)))
AB2 = np.absolute(addMatrices(lambdaScale*A,lambdaScale*B))
AB3 = np.absolute(addMatrices(lambdaScale*B,lambdaScale*A))

print(f'Are the 3 methods equal?: {np.allclose(AB1, AB2) and np.allclose(AB2, AB3) and np.allclose(AB3,AB1)}')



[[ 0.23901029 -0.1130425   0.61594335 -0.36079053]
 [-0.82081751 -0.21583397  0.02955139 -0.21745713]
 [-0.08910826  0.151652   -0.48442856 -0.17096043]]

[[ 0.23901029 -0.1130425   0.61594335 -0.36079053]
 [-0.82081751 -0.21583397  0.02955139 -0.21745713]
 [-0.08910826  0.151652   -0.48442856 -0.17096043]]

[[ 0.23901029 -0.1130425   0.61594335 -0.36079053]
 [-0.82081751 -0.21583397  0.02955139 -0.21745713]
 [-0.08910826  0.151652   -0.48442856 -0.17096043]]
Are the 3 methods equal?: True


# Exercise 6

Solve exercise 5-6 in the book and compare your manual method the the normal @ operator to multiply two matrices.

In [ ]:
# Hints - it can be accomplished using a double for loop and then using the np.dot to
#calculate the dot product between a row from A and a column from B
# remember - if you multiply a m x n matrix by a n x m2 matrix the result
# will be a m x m2 matrix - for easy testing set m = m2 in your example
# matrices.
np.dot( A[rowi,:],B[:,coli] )

# Initialize C - result matrix
C = np.zeros((m,m))  #
#do double for loop and fill out values in C -
for rowi in range(m):
  for coli in range(m):
    # code here...

# Exercise 7

Solve exercise 5-7 from the book.

Repeating the steps (last part of the exercise) with square matrices is optional

# Exercise 8

Solve exercise 5-8 from the book

Remember - when is a matrix symmetric?
When you know the answer to that, you know which two matrices to compare for equality.
\
hints:
you can use np.allclose to test if values in an array are close

https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

# Exercise 9

Solve exercise 5-9 from the book.

Hint:
Create a new matrix where all entries (x,y) have the average of the values from the (x,y) element from A and from A.T.
\
So equal to (A+A.T)/2....

# Exercise 10

Solve exercise 5-10 from the book

# Exercise 11 (optional)


Solve exercise 5-11 from the book

Hint: \
To create a matrix where all elements are square roots for another matrix's element simply use:
\
\
S = np.sqrt(D) \

To create a diagonal matrix use:
np.diag....

# Exercise 12 (optional)


Solve exercise 5-12 from the book